characters = {
    "dizzy": "dizzy",
    "riggs": "riggs",
    "peri": "peri",
    "eunice": "drake",
    "shard": "books",
    "goat": "isaac",
    "hacker": "max",
}

cards = {
    "AbyssalVisions": "Abyssal Visions",
    "Ace": "Ace",
    "AcidCannon": "Acid Cannon",
    "AdaptabilityCard": "Adaptability",
    "AdminDeployCard": "Admin Deploy",
    "AegisCard": "Aegis",
    "AggressiveArmoring": "Aggressive Armoring",
    "AIOverflowCard": "AI Overflow",
    "AresSuperCannon": "War Mode",
    "AresToggleCannon": "Toggle Cannon",
    "AttackDroneCard": "Attack Drone",
    "AvidReader": "Avid Reader",
    "BackupStick": "Backup Stick",
    "Barrage": "Barrage",
    "BasicShieldColorless": "Basic Block",
    "Battalion": "Battalion",
    "BattleRepairs": "Battle Repair",
    "BayOverload": "Bay Overload",
    "BigGun": "Multi Blast",
    "BigShield": "Big Shield",
    "BlockerBurnout": "Blocker Burnout",
    "BlockEvolution": "Block Evolution",
    "BlockParty": "Shield Surge",
    "BlockShot": "Block Shot",
    "BloodstoneBolt": "Bloodstone Bolt",
    "BoltCard": "Bolt",
    "BoostCapacitors": "Boost Capacitors",
    "BoulderPack": "Boulder Bundle",
    "BranchPrediction": "Branch Prediction",
    "BruiseCard": "Bruise",
    "BubbleField": "Bubble Field",
    "Buckshot": "Buckshot",
    "ButtonMash": "Button Mash",
    "CannonColorless": "Basic Shot",
    "CardEnemyGetsStatuses": "Status Time",
    "CatchCard": "Catch",
    "CATTempFixCard": "Quick Fix",
    "ChargeBeam": "Charge Beam",
    "ChipShot": "Chip Shot",
    "ChiselAndSledgeCard": "Chisel and Sledge",
    "CleanExhaustCard": "Clean Exhaust",
    "CloudSaveCard": "Cloud Save",
    "ColorlessBooksSummon": "Books.EXE",
    "ColorlessCATSummon": "CAT.EXE",
    "ColorlessDizzySummon": "Dizzy.EXE",
    "ColorlessDrakeSummon": "Drake.EXE",
    "ColorlessIsaacSummon": "Isaac.EXE",
    "ColorlessMaxSummon": "Max.EXE",
    "ColorlessPeriSummon": "Peri.EXE",
    "ColorlessPeriSummonNoDesc": "Peri.EXE",
    "ColorlessRiggsSummon": "Riggs.EXE",
    "ColorlessTrash": "Trash",
    "CombustionEngine": "Combustion Engine",
    "Converter": "Converter",
    "CorrosionBeam": "Corrosion Beam",
    "CorruptedCore": "Corrupted Core",
    "DefensiveMode": "Defensive Mode",
    "Deflection": "Deflection",
    "DesperateMeasures": "Desperate Measures",
    "DiceRoll": "Dice Roll",
    "DodgeColorless": "Basic Dodge",
    "DraculaCard": "Leech",
    "DrawCannon": "Draw Shot",
    "DrawThree": "Quick Thinking",
    "DroneShiftCard": "Parallel Shift",
    "DroneshiftColorless": "Basic Shift",
    "DroneTurnCard": "Radio Control",
    "DualStun": "Multi Stun",
    "EchoCard": "Echo",
    "EMPCard": "EMP",
    "EMPSlug": "EMP Slug",
    "EndlessMagazine": "Endless Magazine",
    "EnergyDroneCard": "Energy Drone",
    "EngineMisfireCard": "Engine Misfire",
    "Enrage": "Enrage",
    "EntropyExploit": "Entropy Exploit",
    "EphemeralCannon": "Ephemeral Blast",
    "EphemeralDodge": "Ephemeral Dodge",
    "EphemeralRepairs": "Ephemeral Repairs",
    "EscapeArtist": "Escape Artist",
    "EvasiveShot": "Evasive Shot",
    "EvilRiggsCard": "Missile Swarm",
    "ExhaustHandCard": "Total Cache Wipe",
    "ExothermicRelease": "Exothermic Release",
    "Fear": "Fear",
    "Feint": "Feint",
    "Firewall": "Firewall",
    "FlashFirmware": "Flash Firmware",
    "FlashPoint": "Flash Point",
    "FleetfootCard": "Fleetfoot",
    "FlexMove": "Flex Move",
    "FourthCardTest": "Fourth Card Test",
    "FreezeDry": "Freeze Dry",
    "FumeCannon": "Frontloaded Blast",
    "GarnetGatling": "Garnet Gatling",
    "GenesisCanister": "Genesis Canister",
    "GenesisDevice": "Genesis Device",
    "GeodeCard": "Ol' Reliable",
    "Glimmershot": "Glimmer Shot",
    "Glissade": "Glissade",
    "HandCannon": "Hand Cannon",
    "HandOffCard": "Hand Off",
    "HealthCannon": "Pillage and Plunder",
    "HeatSink": "Heatsink",
    "Heatwave": "Heatwave",
    "HeavyMissileCard": "Heavy Missile",
    "HellsHeartCard": "From Hell's Heart",
    "HESlug": "Explosive Slug",
    "HotCompress": "Hot Compress",
    "Hotfoot": "Hotfoot",
    "IFrameCard": "I Frames",
    "IndestructibleDroneCard": "WALL",
    "Inverter": "Inverter",
    "JackOfAllTrades": "Jack of All Trades",
    "Juke": "Juke",
    "Jumble": "Jumble",
    "JupiterCannonSummon": "Jupiter's Moons",
    "JupiterSuperCannonSummon": "Jupiter Eclipse",
    "JustABigAttackCard": "Just A Big Attack",
    "JustAGoodAttackCard": "Just A Good Attack",
    "LargeBoulder": "Large Boulders",
    "LazyBarrage": "Lazy Barrage",
    "LibraCard": "Flux",
    "LightningBottle": "Lightning in a Bottle",
    "LoadStateCard": "Load State",
    "Lunge": "Lunge",
    "MageHand": "Mage Hand",
    "MagiBattery": "Magi- Battery",
    "MakeColorlessTrash": "Make Trash",
    "MathMaxCard": "Math.Max",
    "MaxTrashGeneration": "Memory Leak",
    "MedusaField": "Medusa Field",
    "MeteorCard": "Meteor",
    "MineralDeposit": "Mineral Deposit",
    "MiniMe": "Jupiter Drone",
    "MiningDrillCard": "Mining Drill",
    "MissileLaunchCard": "Missile Shot",
    "MissileMalware": "Missile Malware",
    "MissingShieldAttack": "Who Needs Shields",
    "MitosisCard": "Mitosis",
    "MomentumCard": "Momentum",
    "MultiShot": "Multi Shot",
    "NonTempTrash": "Debris",
    "NowOrNeverCard": "Now Or Never",
    "OptionsCard": "Options",
    "Overclock": "Overclock",
    "Overdrive": "Escalate",
    "OverflowingPower": "Overflowing Power",
    "OverflowingPowerAlt": "Overflowing Power Alt",
    "Overpower": "Overpower",
    "OxygenLeak": "Oxygen Leak",
    "Panic": "Panic",
    "Parry": "Parry",
    "PaybackCard": "Payback",
    "Pebble": "Pebble",
    "PerfectSpecimen": "Perfect Specimen",
    "PointlessOverkill": "Pointless Overkill",
    "PowerdriveCard": "Power Play",
    "PrepareCard": "Prepare",
    "PrismAttackCard": "Prism",
    "PulseBarrierCard": "Pulse Barrier",
    "QuantumQuarryCard": "Quantum Quarry",
    "ReclaimedEnergy": "Reclamation",
    "RefreshInterval": "Refresh Interval",
    "ReleaseCard": "Release",
    "RepairKitCard": "Repair Kit",
    "RerollCard": "Reroll",
    "RerollCardTestReplacement": "Reroll Alt",
    "RerouteCard": "Reroute",
    "ReturnFireCard": "Return Fire",
    "RevTheEngines": "Rev the Engines",
    "RockFactory": "Rock Factory",
    "RootAccess": "Root Access",
    "SashaSoccerCard": "Sport Orb",
    "SaveStateCard": "Save State",
    "ScatterShot": "Scattershot",
    "ScootRight": "Scoot",
    "Scramble": "Scramble",
    "SearCard": "Sear",
    "SecondOpinions": "Second Opinions",
    "SeekerMissileCard": "Seeker",
    "SelectiveMemory": "Selective Memory",
    "SelfControl": "Self Control",
    "Serenity": "Serenity",
    "SevenCard": "Lucky Seven",
    "Shackle": "Shackle",
    "ShardCard": "Crystal Shard",
    "ShardPack": "Shardpack",
    "Shardsource": "Sapphire Shield",
    "SharpTrash": "Hazards",
    "ShieldDroneCard": "Shield Drone",
    "ShieldGun": "Shield Gun",
    "ShieldMomentumAlt": "Shield Momentum Alt",
    "ShiftShot": "Shift Shot",
    "ShuffleShot": "Shuffle Shot",
    "Sidestep": "Sidestep",
    "SiegeMode": "Siege Mode",
    "SmallBoulder": "Small Boulder",
    "SmallFrag": "Small Fragment",
    "SolarBreeze": "Solar Breeze",
    "SolarFlair": "Solar Flair",
    "SpaceMineCard": "Space Mine",
    "Spacer": "Spacer",
    "SpareBattery": "Extra Battery",
    "Strafe": "Strafe",
    "StrikerSquadron": "Striker Squadron",
    "StunCharge": "Stun Charge",
    "StunShot": "Stun Shot",
    "StunSourceCard": "Stun Source",
    "SuperSink": "Absolute Zero",
    "SwizzleShift": "Swizzle Shift",
    "SystemSecurity": "System Security",
    "TableFlipCard": "Table Flip",
    "TemporalAnomalyCard": "Temporal Anomaly",
    "ThermalBattery": "Thermal Battery",
    "ThinkTwice": "Think Twice",
    "TimestopCard": "Time Skip",
    "Toxic": "Toxic",
    "TrashAnchor": "Anchor",
    "TrashAnnoyance": "Annoyance",
    "TrashAutoShoot": "Safety Override",
    "TrashExhaustOthers": "Static Noise",
    "TrashFumes": "Fumes",
    "TrashMiasma": "Miasma",
    "TrashUnplayable": "Comm Jam",
    "TrashZeroSmasher": "Distraction",
    "TurbineGenerators": "Turbine Generators",
    "UnpoweredShardCard": "Unpolished Crystal",
    "UnstableCore": "Unstable Core",
    "Vamoose": "Vamoose",
    "Ventilator": "Ventilator",
    "VolatileVaporCard": "Volatile Vapor",
    "WaltzCard": "Waltz",
    "WaveBeam": "Wave Beam",
    "WaveCharge": "Wave Charge",
    "WeakenHull": "Weaken Hull",
    "Whiplash": "Whiplash",
    "WormFood": "Worm",
    "YellowCardTrash": "",
    "ZeroDraw": "Zero Draw",
    "ZExpensiveCardMaker": "please. sir. my dollars",
    "ZirconZip": "Zircon Zip",
    "ZMoveEnemyTest": "lets move around, yahoo",
    "ZOverheatTest": "dont play this",
    "ZSilverTest": "do this look right",
    "ZTestCrowdedCard": "Crowded Card",
    "ZTestCrowdedCard2": "Really Really Crowded Card",
    "ZTestDeleteACharacterCard": "Delete Dizzy From Time",
    "ZTestDisabledAction": "The Heat Is Disabled",
    "ZTestShiftCard": "do this look right",
    "ZTestStatusSet": "The Shield Is Set",
}

artifacts = {
    "AdaptivePlating": "ADAPTIVE PLATING",
    "AresCannon": "ARES CANNON",
    "AresCannonV2": "ARES CANNON V2",
    "ArmoredBay": "ARMORED BAY",
    "BerserkerDrive": "BERSERKER DRIVE",
    "BlastArmor": "BLAST ARMOR",
    "BrokenGlasses": "BROKEN GLASSES",
    "Bubbler": "BUBBLER",
    "CaffeineRush": "CAFFEINE RUSH",
    "CargoHold": "CARGO HOLD",
    "CockpitTarget": "COCKPIT LOCK-ON",
    "ControlRods": "CONTROL RODS",
    "ControlRodsV2": "CONTROL RODS V2",
    "Crosslink": "CROSSLINK",
    "DailyModeTracker": "DAILY MODE",
    "DailyAdjustedMindset": "DAILY MODIFIER: ADJUSTED MINDSET",
    "DailyBossBinaryStar": "DAILY MODIFIER: BINARY BOSSES",
    "DailyCorrupted": "DAILY MODIFIER: CORE CORRUPTION",
    "DailyScaffold": "DAILY MODIFIER: SCAFFOLDS",
    "DailyShuffler": "DAILY MODIFIER: SHUFFLER",
    "DailyJustOneCharacter": "DAILY MODIFIER: SOLO RUN",
    "DailyHealthEmUp": "DAILY MODIFIER: SWORD AND SHIELD",
    "DailyThinDeck": "DAILY MODIFIER: THIN DECK",
    "DakkaDrum": "DAKKA DRUM",
    "DemonThrusters": "DEMON THRUSTERS",
    "DirtyEngines": "DIRTY ENGINES",
    "DronePiercer": "DRONE PIERCER",
    "EnergyRefund": "ENERGY REFUND",
    "FlowState": "FLOW STATE",
    "Flywheel": "FLYWHEEL",
    "FractureDetection": "FRACTURE DETECTION",
    "GeminiCore": "GEMINI CORE",
    "GeminiCoreBooster": "GEMINI CORE BOOSTER",
    "Genesis": "GENESIS",
    "GlassCannon": "GLASS CANNON",
    "GravelRecycler": "GRAVEL RECYCLER",
    "GrazerBeam": "GRAZER BEAM",
    "Grimoire": "GRIMOIRE",
    "HARDMODE": "HARDMODE",
    "HealBooster": "HEAL BOOSTER",
    "HeatDistiller": "HEAT DISTILLER",
    "HiFreqIntercom": "HI FREQ INTERCOM",
    "HullPlating": "HULL PLATING",
    "HunterWings": "HUNTER WINGS",
    "IgnitionCoil": "IGNITION COIL",
    "InitialBooster": "INITIAL BOOSTER",
    "IonConverter": "ION CONVERTER",
    "JetThrusters": "JET THRUSTERS",
    "JettisonHatch": "JETTISON HATCH",
    "JumperCables": "JUMPER CABLES",
    "JupiterDroneHub": "JUPITER DRONE HUB",
    "JupiterDroneHubV2": "JUPITER DRONE HUB V2",
    "LightspeedBootDisk": "LIGHTSPEED BOOT DISK",
    "MultiThreading": "MULTI THREADING",
    "NanofiberHull": "NANOFIBER HULL",
    "NextGenInsulation": "NEXT GEN INSULATION",
    "Overcharger": "OVERCHARGER",
    "OverclockedGenerator": "OVERCLOCKED GENERATOR",
    "PerpetualMotionDevice": "PERPETUAL MOTION DEVICE",
    "DizzyBoost": "PHOTON CONDENSER",
    "Piercer": "PIERCER",
    "PowerDiversion": "POWER DIVERSION",
    "Premeditation": "PREMEDITATION",
    "EnergyPrep": "PREPPED BATTERIES",
    "PressureFuse": "PRESSURE FUSE",
    "Prototype22": "PROTOTYPE 22",
    "Quickdraw": "QUICKDRAW",
    "RadarSubwoofer": "RADAR SUBWOOFER",
    "Recalibrator": "RECALIBRATOR",
    "Redwall": "REDWALL",
    "Regenerator": "REGENERATOR",
    "ResonanceFork": "RESONANCE FORK",
    "RevengeDrive": "REVENGE DRIVE",
    "RicochetPaddle": "RICOCHET PADDLE",
    "RockCollection": "ROCK COLLECTION",
    "SafetyLock": "SAFETY LOCK",
    "SalvageArm": "SALVAGE ARM",
    "ScrapArmor": "SCRAP ARMOR",
    "ShardCollector": "SHARD COLLECTOR",
    "ShardEnchanter": "SHARD ENCHANTER",
    "SharpEdges": "SHARP EDGES",
    "ShieldBurst": "SHIELD BURST",
    "ShieldMemory": "SHIELD MEMORY",
    "ShieldReserves": "SHIELD RESERVES",
    "Simplicity": "SIMPLICITY",
    "StandbyMode": "STANDBY MODE",
    "StickyNote": "STICKY NOTE",
    "StrongStart": "STRONG START",
    "StunCalibrator": "STUN CALIBRATOR",
    "SubzeroHeatsinks": "SUBZERO HEATSINKS",
    "SummonControl": "SUMMON CONTROL",
    "CobaltArtifact": "THE COBALT CORE",
    "ThermoReactor": "THERMO REACTOR",
    "TideRunner": "TIDE RUNNER",
    "TridimensionalCockpit": "TRIDIMENSIONAL COCKPIT",
    "WarpMastery": "WARP MASTERY",
    "ShieldPrep": "WARP PREP",
    "GoatThrusters": "WAVE CONTROL",
    "WeightedScales": "WEIGHTED SCALES",
    "ZeroDoubler": "ZERO DOUBLER",
}
